"""Layer indexing and toolpath parsing."""
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from klipper_tui.gcode import (
    index_layers,
    index_layers_by_z,
    layer_for_position,
    read_layer,
)

failures = []


def check(name, condition, detail=""):
    if not condition:
        failures.append(f"{name}: {detail}")


def write(text):
    handle = tempfile.NamedTemporaryFile("w", suffix=".gcode", delete=False)
    handle.write(text)
    handle.close()
    return handle.name


# PrusaSlicer style: explicit layer markers with a Z comment.
prusa = write(
    "; generated by PrusaSlicer\n"
    "G21\nG90\nM83\n"
    ";LAYER_CHANGE\n;Z:0.2\n"
    "G1 X0 Y0\n"
    "G1 X10 Y0 E1\n"
    "G1 X10 Y10 E1\n"
    ";LAYER_CHANGE\n;Z:0.4\n"
    "G1 X0 Y10 E1\n"
    "G1 X0 Y0 E1\n"
)
layers = index_layers(prusa)
check("two layers found", len(layers) == 2, f"{len(layers)}")
check("heights read", [l.z for l in layers] == [0.2, 0.4],
      f"{[l.z for l in layers]}")

path = read_layer(prusa, layers[0])
check("first layer segments", len(path.segments) == 2, f"{len(path.segments)}")
check("extrusion detected", all(s.extruding for s in path.segments))
check("bounds", path.bounds() == (0.0, 0.0, 10.0, 10.0), f"{path.bounds()}")

# Travel moves carry no E and must be distinguishable.
travel = write(
    ";LAYER_CHANGE\n;Z:0.2\n"
    "G1 X0 Y0\n"
    "G1 X5 Y5\n"            # travel
    "G1 X10 Y5 E1\n"        # extrusion
)
path = read_layer(travel, index_layers(travel)[0])
kinds = [s.extruding for s in path.segments]
check("travel then extrusion", kinds == [False, True], f"{kinds}")

# Relative extrusion: a negative E is a retraction, not material.
retract = write(
    ";LAYER_CHANGE\n;Z:0.2\nM83\n"
    "G1 X0 Y0\n"
    "G1 X10 Y0 E-2\n"       # retraction while moving
    "G1 X10 Y10 E1\n"
)
path = read_layer(retract, index_layers(retract)[0])
kinds = [s.extruding for s in path.segments]
check("retraction is not extrusion", kinds == [False, True], f"{kinds}")

# Cura style numbering.
cura = write(
    ";LAYER:0\nG1 X0 Y0\nG1 X5 Y0 E1\n"
    ";LAYER:1\nG1 X5 Y5 E1\n"
)
check("cura markers understood", len(index_layers(cura)) == 2)

# No comments at all: fall back to splitting on Z moves.
bare = write(
    "G1 Z0.2\nG1 X0 Y0\nG1 X5 Y0 E1\n"
    "G1 Z0.4\nG1 X5 Y5 E1\n"
)
by_z = index_layers_by_z(bare)
check("z fallback finds layers", len(by_z) == 2, f"{len(by_z)}")
check("z fallback heights", [l.z for l in by_z] == [0.2, 0.4],
      f"{[l.z for l in by_z]}")

# Mapping the printer's file position onto a layer.
check("position inside the first layer",
      layer_for_position(layers, layers[0].start + 1) == 0)
check("position inside the second",
      layer_for_position(layers, layers[1].start + 1) == 1)
check("past the end clamps to the last",
      layer_for_position(layers, 10 ** 9) == 1)
check("no layers is handled", layer_for_position([], 5) is None)

# Offsets must rise through the file, so progress can be compared against them.
path = read_layer(prusa, layers[0])
offsets = [s.offset for s in path.segments]
check("offsets increase", offsets == sorted(offsets), f"{offsets}")
check("offsets sit inside the layer",
      all(layers[0].start <= o < layers[0].end for o in offsets))

for f in failures:
    print("FAIL", f)
print("gcode: all checks passed" if not failures else f"{len(failures)} failed")
sys.exit(1 if failures else 0)
